# Generated by Django 5.1.5 on 2025-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_class_teacher_classteacher_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='standard_code',
            field=models.CharField(blank=True, help_text='행정표준코드를 입력하세요.', max_length=10, verbose_name='행정표준코드'),
        ),
    ]
