# Generated by Django 5.1.5 on 2025-09-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_school_standard_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='education_office_code',
            field=models.CharField(blank=True, help_text='시도교육청코드를 입력하세요.', max_length=10, verbose_name='시도교육청코드'),
        ),
    ]
