# Generated by Django 5.1.5 on 2025-10-01 17:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_school_education_office_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '알레르기 유발 식품',
                'verbose_name_plural': '알레르기 유발 식품',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMeal',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_date', models.DateField(verbose_name='급식 날짜')),
                ('meal_type', models.CharField(choices=[('breakfast', '조식'), ('lunch', '중식'), ('dinner', '석식')], default='lunch', max_length=20, verbose_name='식사 구분')),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='칼로리 (kcal)')),
                ('raw_meal_name', models.TextField(verbose_name='요리명 원본')),
                ('origin_information', models.TextField(blank=True, verbose_name='원산지 정보')),
                ('nutrition_information', models.TextField(blank=True, verbose_name='영양 정보')),
                ('served_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='급식 인원수')),
                ('source_updated_at', models.DateField(blank=True, null=True, verbose_name='원본 데이터 최종 수정 일자')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='정보 가져온 시각')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학교 급식 정보',
                'verbose_name_plural': '학교 급식 정보',
                'unique_together': {('school', 'meal_date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='SchoolMealItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='식단명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('allergens', models.ManyToManyField(blank=True, to='nutrition.allergen', verbose_name='알레르기 유발 식품')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.schoolmeal', verbose_name='급식')),
            ],
            options={
                'verbose_name': '학교 급식 항목',
                'verbose_name_plural': '학교 급식 항목',
            },
        ),
        migrations.CreateModel(
            name='StudentAllergy',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.allergen', verbose_name='알레르기 요소')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 알레르기 정보',
                'verbose_name_plural': '학생 알레르기 기록',
                'unique_together': {('student', 'allergen')},
            },
        ),
    ]
