# Generated by Django 5.2.1 on 2025-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhabittracker',
            name='promise_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='약속 실천 방법'),
        ),
    ]
