# Generated by Django 5.1.5 on 2025-07-29 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('current_course_id', models.IntegerField(blank=True, null=True, verbose_name='현재 코스 ID')),
                ('current_content_id', models.IntegerField(blank=True, null=True, verbose_name='현재 콘텐츠 ID')),
                ('workspace_state', models.JSONField(default=dict, verbose_name='워크스페이스 상태')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '에이전트 세션',
                'verbose_name_plural': '에이전트 세션',
            },
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='프롬프트')),
                ('ai_provider', models.CharField(choices=[('claude', 'Claude'), ('gemini', 'Gemini'), ('chatgpt', 'ChatGPT'), ('grok', 'Grok')], max_length=20, verbose_name='AI 프로바이더')),
                ('content_type', models.CharField(max_length=50, verbose_name='콘텐츠 타입')),
                ('generated_content_id', models.IntegerField(blank=True, null=True, verbose_name='생성된 콘텐츠 ID')),
                ('success', models.BooleanField(default=True, verbose_name='성공 여부')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='처리 시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 생성 로그',
                'verbose_name_plural': 'AI 생성 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
