# Generated by Django 5.2.1 on 2025-07-23 15:35

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PAPSActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SHUTTLE_RUN', '왕복오래달리기'), ('LONG_RUN_WALK', '오래달리기 걷기'), ('STEP_TEST', '스텝검사'), ('SIT_REACH', '앉아윗몸앞으로굽히기'), ('COMPREHENSIVE_FLEXIBILITY', '종합유연성'), ('PUSH_UP', '팔굽혀펴기'), ('SIT_UP', '윗몸 말아올리기'), ('GRIP_STRENGTH', '악력'), ('FIFTY_METER_RUN', '50m 달리기'), ('STANDING_LONG_JUMP', '제자리멀리뛰기'), ('BMI', '체질량 지수(BMI) 측정'), ('CARDIO_PRECISION_TEST', '심폐지구력정밀평가'), ('BODY_FAT_RATE_TEST', '체지방률평가'), ('POSTURE_TEST', '자세평가'), ('SELF_BODY_TEST', '자기신체평가')], max_length=50, unique=True)),
                ('category_id', models.UUIDField()),
                ('measurement_schema', models.JSONField()),
                ('evaluation_criteria', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAPSCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CARDIO', '심폐지구력'), ('FLEXIBILITY', '유연성'), ('STRENGTH', '근력/근지구력'), ('AGILITY', '순발력'), ('BODY_FAT', '체지방'), ('CARDIO_PRECISION', '심폐지구력정밀평가'), ('BODY_FAT_RATE', '체지방률평가'), ('POSTURE', '자세평가'), ('SELF_BODY', '자기신체평가')], max_length=30, unique=True)),
                ('evaluation_type', models.CharField(choices=[('REQUIRED', '필수평가'), ('OPTIONAL', '선택평가')], max_length=20)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PAPSSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('school_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('session_type', models.CharField(choices=[('REGULAR', '정시'), ('SUPPLEMENTARY', '수시')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('measurement_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-school_year', '-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='PAPSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('student_id', models.IntegerField()),
                ('activity_id', models.UUIDField()),
                ('measured_by_teacher_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('student_grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('measurement_data', models.JSONField()),
                ('evaluation_grade', models.CharField(blank=True, choices=[('1', '1등급'), ('2', '2등급'), ('3', '3등급'), ('4', '4등급'), ('5', '5등급')], max_length=2)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-measured_at'],
                'unique_together': {('session_id', 'student_id', 'activity_id')},
            },
        ),
        migrations.CreateModel(
            name='PAPSSessionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('grade', models.IntegerField(choices=[(4, '초등학교 4학년'), (5, '초등학교 5학년'), (6, '초등학교 6학년'), (7, '중학교 1학년'), (8, '중학교 2학년'), (9, '중학교 3학년'), (10, '고등학교 1학년'), (11, '고등학교 2학년'), (12, '고등학교 3학년')], validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('category_id', models.UUIDField()),
                ('activity_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('session_id', 'grade', 'category_id')},
            },
        ),
    ]
