# Generated by Django 5.1.5 on 2025-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_education', '0002_alter_papscategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='papssessionactivity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 상태'),
        ),
    ]
