# Generated by Django 5.1.5 on 2025-07-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_education', '0003_papssessionactivity_is_active'),
    ]

    operations = [
        # Remove the existing unique_together constraint
        migrations.AlterUniqueTogether(
            name='papssessionactivity',
            unique_together=set(),
        ),
        
        # Add a new unique constraint that includes is_active=True
        # This allows multiple records for the same session/grade/category as long as only one is active
        migrations.AddConstraint(
            model_name='papssessionactivity',
            constraint=models.UniqueConstraint(
                fields=['session_id', 'grade', 'category_id'],
                condition=models.Q(is_active=True),
                name='unique_active_session_grade_category'
            ),
        ),
    ]
