# Generated by Django 5.1.5 on 2025-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_education', '0004_fix_session_activity_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='papssessionactivity',
            constraint=models.UniqueConstraint(fields=('session_id', 'grade', 'category_id', 'activity_id'), name='unique_session_grade_category_activity'),
        ),
    ]
