# Generated by Django 5.1.5 on 2025-08-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_education', '0006_alter_papsrecord_evaluation_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papsrecord',
            name='measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
